language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  matrix:
    - DB=mysql db_dsn='mysql://travis@127.0.0.1/geodistance_test'
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 5.5
      env: PHPCS=1 DEFAULT=0
    - php: 5.5
      env: COVERALLS=1 DEFAULT=0 DB=mysql db_dsn='mysql://travis@127.0.0.1/geodistance_test'

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE geodistance_test;'; fi"
  - command -v phpenv > /dev/null && phpenv rehash || true
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"

script:
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=vendor --ignore=docs --ignore=tests/bootstrap.php . ; fi"
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then phpunit --stderr --coverage-clover build/logs/clover.xml; fi"

after_script:
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/coveralls -v; fi"
